### PR TITLE
Modify script for object-oriented and browser compatibility

### PR DESCRIPTION
**Pull request by Baptistou**
Normally it should work on Firefox Desktop 52, Chrome, Opera, and Firefox Android.
SVG icons are not supported on Chrome, use png instead.

### CODE REVIEW

**Comment by log69** [comment]
Hi, some comments:

I'd rather tell you not to use the "browser" object but rather "chrome". It
gives an extra unnecessary abstraction. If Mozilla's goal is to implement
Chrome's extension API, then it should be. You can create it the other way
around if necessary in the future. Until then, it is nice to keep a simple
structure I think.

I do not touch PNG images even if it's incompatible. I go only with SVG.
Chrome will implement it by time hopefully. The Chrome extension can
replace the SVG images with PNG when being built.

I don't like your object oriented approach because it doesn't help keep the
complexity level as low as possible. It again adds unnecessary complexity.
You're using browser.tabs inside your class and outside of it too. The
events are not clearly separated from the helper functions.

I wouldn't use prototypes either because it might break functionality with
other codes. It gives a hidden chance for bugs if not watched carefully in
the future when code base grow.

You're using global variables.

It's no sense to use an object if it is the only single and common one for
the whole code, sharing their data. Have you checked whether the event
calls can cause complicated bugs because of the global variables? What if
the events kick in at the wrong time? Is there any chance that the
variables will be accessed the same time?

The problem is that you handle the "urls" array from several async calls.
The result of the array will greatly depend on which call will get there
first. Have you tested it? Can you find a logical problem there in regards
of the async methods?

If you can take a new approach, I gladly merge your code. I appreciate your
help.

Thanks,
Andras

**Comment by Baptistou** [comment]
Hi Andras,

Currently, I think 'browser' and 'chrome' are just aliases to the same API but I prefered to use the neutral 'browser' keyword instead of the Google proprietary 'chrome' keyword.

Concerning SVG icons, it was just to inform you that Google Chrome throws an error when calling browser.browserAction.setIcon with SVG format. You are free to use the format you prefer.
I just try to be as cross-browser and conform as possible :)

This is the difficult choice between using a more developper-friendly object-oriented code and a more low-complexity code. The object-oriented approach is time saving if you want to maintain and debug the application in long term and add new features.
The browser.tabs inside the class initializes the class variables --> constructor
The thing interesting here is that the constructor is async but, as other function calls in main process are also async and dependent on user event, class variables are correctly initialized before other function calls. That's why I seperated the two browser.tabs and share the global variable for the whole code.
Moreover, even if you add two listeners to the same event in different part of the code, the listeners are executed sequentially (not in parallel) in the same order you added them. Thus variables are accessed and modified synchronously.
If you are not convinced, I a little copied the same object oriented code from another WebExtension I made and I don't have any issue with async calls.
AMO: https://addons.mozilla.org/fr/firefox/addon/popupfilteraddon/
GitHub: https://github.com/Baptistou/PopupFilter
Currently tested and working on Firefox Desktop & Android, Chrome and Opera.

You can replace the two prototype methods by classical functions if you want, it was just more convenient for me.

Baptiste

**Comment by log69** [comment]
Hi, what is the purpose and sense to bring in the
chrome.windows.onFocusChanged extra event? I do not see what it helps in.
I'd appreciate if you explained it, thank you.


On Wed, Oct 25, 2017 at 10:34 PM, Baptiste Thémine <notifications@github.com

**Comment by log69** [comment]
I decided to drop localStorage and replace it with chrome.storage.local,
thanks for testing it on Android. I'd like to skip the OO code to be able
to provide as easy to understand as possible if anyone intends to audit it.

Unfortunately I will have to use global variables too.

**Comment by log69** [comment]
Hi, I tested your code on Android and it doesn't work. The YesScript2 icon
appears in the Firefox browser's menu but tapping it doesn't do anything.
Meanwhile I've refactored my code by dropping localStorage for
chrome.storage.local.

**Comment by Baptistou** [comment]
Hi, browser.windows.onFocusChanged is necessary if you have tabs opened in different windows. Because browser.tabs.onActivated is triggered only if you switch from a tab to another within the same window, not if you switch from a window to another.
I haven't tested my code on Android yet so maybe I forgot something in the code. I will do it this weekend and I will inform you if I managed to make it work.

**Comment by log69** [comment]
Thanks.

On Fri, Oct 27, 2017 at 11:39 AM, Baptiste Thémine <notifications@github.com

**Comment by Baptistou** [comment]
Good news ! I tested my code on Firefox Android Nightly and it is working !
I used the same code as in this pull request. I didn't modify anything.

**Comment by log69** [comment]
Thanks Baptiste, I will check it out later.

**Comment by log69** [comment]
Hi, a notification: I'm still in some kind of work and did not have the
time to check what you wrote. Excuse my late reply, I'll check it next
week. Thanks.

**Comment by Baptistou** [comment]
Ok no problem ;)
I would like also to use my code for my existing addon. I think it could be nice to combine a script blocker and a popup blocker. I plan to release it either as an update or as a complementary addon in the coming weeks. Does it annoy you if I add it on AMO?

**Comment by log69** [comment]
No, not at all, feel free to utilize anything from what we talked about.
And first of all it was your brilliant idea to incorporate CSP and give a
solution with it for the problem. And also it's nice to have more solutions
than less. Thanks.

**Pull request closed without merging**
